services:
  web:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://caresignal_app:${APP_ROLE_PASSWORD}@db:5432/postgres
      WORKER_DATABASE_URL: postgres://caresignal_worker:${WORKER_ROLE_PASSWORD}@db:5432/postgres
      REDIS_HOST: redis
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - "8000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  db_data:
  redis_data:
  grafana_data:
  prometheus_data:
